name: 'Setup and build plugin'
description: 'Builds the plugin for specified architecture and build config.'
inputs:
  target:
    description: 'Build target for dependencies'
    required: true
  config:
    description: 'Build configuration'
    required: false
    default: 'Release'
  codesign:
    description: 'Enable codesigning (macOS only)'
    required: false
    default: 'false'
  codesignIdent:
    description: 'Developer ID for application codesigning (macOS only)'
    required: false
    default: '-'
  visualStudio:
    description: 'Visual Studio version (Windows only)'
    required: false
    default: 'Visual Studio 16 2019'
  workingDirectory:
    description: 'Working directory for packaging'
    required: false
    default: ${{ github.workspace }}
runs:
  using: 'composite'
  steps:
    - name: Run Windows Build
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        # Build 32bit directshow filter only
        $Build32Args = @{
          Target = 'x86'
          Configuration = '${{ inputs.config }}'
          CMakeGenerator = '${{ inputs.visualStudio }}'
        }

        ${{ inputs.workingDirectory }}/.github/scripts/Build-Windows.ps1 @Build32Args

        $BuildArgs = @{
          Target = '${{ inputs.target }}'
          Configuration = '${{ inputs.config }}'
          CMakeGenerator = '${{ inputs.visualStudio }}'
        }

        if ( ( Test-Path env:CI ) -and ( Test-Path env:RUNNER_DEBUG ) ) {
          $BuildArgs += @{
            Debug = $true
          }
        }

        ${{ inputs.workingDirectory }}/.github/scripts/Build-Windows.ps1 @BuildArgs
